#!/usr/bin/env python

import argparse
import pathlib
import subprocess
import re
import webbrowser
from collections.abc import Iterable, Sequence, Generator

RED = "\033[1;31m"
GREEN = "\033[1;32m"
YELLOW = "\033[1;33m"
BLUE = "\033[1;34m"
MAGENTA = "\033[1;35m"
CYAN = "\033[1;36m"
GREY = "\033[38;5;240m"
BOLD = "\033[1m"
RESET = "\033[0m"


def colour(text: str, colour_: str) -> str:
    """
    Return the text in the given colour.
    """

    return f"{colour_}{text}{RESET}"


def _run_git_cmd(
    args: Iterable[str],
    git_dir: pathlib.Path | None = None,
    print_cmd: bool = False,
) -> Generator[str]:
    cmds = ("git",) if git_dir is None else ("git", "-C", git_dir)
    if print_cmd:
        print(colour(" ".join((*cmds, *args)), BLUE + BOLD))

    # https://stackoverflow.com/a/4417735
    popen = subprocess.Popen(
        args=(*cmds, *args),
        stdout=subprocess.PIPE,
        universal_newlines=True,
    )
    if popen.stdout:
        for line in popen.stdout:
            yield line.rstrip("\n")
    if popen.stderr:
        for line in popen.stderr:
            yield line.rstrip("\n")

    popen.wait()
    if popen.returncode != 0:
        raise RuntimeError("git push returned a non-zero exit code")


def _get_branch_name() -> str:
    status = "\n".join(_run_git_cmd(("status",)))
    matched, = re.findall("On branch ([0-9A-Za-z_-]+)", status)
    if matched:
        return matched
    else:
        raise ValueError("branch name not found")


def _get_remote_url() -> str:
    origin_name = "origin"
    return "\n".join(
        _run_git_cmd(
            ("remote", "get-url", origin_name),
            print_cmd=False,
        )
    )


def _ssh_to_http(ssh_url: str) -> str:
    ssh_pattern = r"git@([\w.]+):([\w-]+)/([\w-]+)"
    matches = re.compile(ssh_pattern).findall(ssh_url)
    if not matches:
        raise ValueError(f"Could not handle SSH remote with URL '{ssh_url}'. Expected URL with pattern '{ssh_pattern}'")

    host, owner, repo = matches[0]
    return f"https://{host}/{owner}/{repo}"


def _github_pull_request_url(host_url: str, branch_name: str) -> str:
    return f"{host_url}/pull/new/{branch_name}"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--push",
        action=argparse.BooleanOptionalAction,
        default=False,
    )
    args = parser.parse_args(argv)

    remote_url = _get_remote_url()
    if remote_url.startswith("git@"):
        try:
            http_url = _ssh_to_http(remote_url)
        except ValueError as e:
            print(colour(f"error: {e}", RED))
            return 1
    else:
        http_url = remote_url

    branch_name = _get_branch_name()
    if http_url.startswith("https://github.com"):
        pull_request_url = _github_pull_request_url(http_url, branch_name)
    else:
        raise NotImplementedError(f"Method not supported for {http_url}")

    if args.push:
        try:
            for line in _run_git_cmd(("push",), print_cmd=True):
                print(line)
        except RuntimeError:
            return 1

    print(colour(f"Opening PR at: {pull_request_url}", GREEN))
    webbrowser.open(pull_request_url)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
