#!/usr/bin/env python

import argparse
import pathlib
import subprocess
import re
import webbrowser
from collections.abc import Iterable, Sequence

RED = "\033[1;31m"
GREEN = "\033[1;32m"
YELLOW = "\033[1;33m"
BLUE = "\033[1;34m"
MAGENTA = "\033[1;35m"
CYAN = "\033[1;36m"
GREY = "\033[38;5;240m"
BOLD = "\033[1m"
RESET = "\033[0m"


def colour(text: str, colour_: str) -> str:
    """
    Return the text in the given colour.
    """

    return f"{colour_}{text}{RESET}"


def _run_git_cmd(
    args: Iterable[str],
    git_dir: pathlib.Path | None = None,
    print_cmd: bool = False,
) -> str:
    cmds = ("git",) if git_dir is None else ("git", "-C", git_dir)
    if print_cmd:
        print(colour(" ".join((*cmds, *args)), BLUE + BOLD))

    proc = subprocess.run(
        args=(*cmds, *args),
        check=True,  # Raise an exception on non-zero return codes
        capture_output=True,
    )
    assert isinstance(proc.stdout, bytes)  # noqa: S101
    return proc.stdout.decode().rstrip()


def _get_branch_name() -> str:
    status = _run_git_cmd(("status",))
    matched, = re.findall("On branch ([0-9A-Za-z_-]+)", status)
    if matched:
        return matched
    else:
        raise ValueError("branch name not found")


def _get_remote_url() -> str:
    origin_name = "origin"
    return _run_git_cmd(
        ("remote", "get-url", origin_name),
        print_cmd=False,
    )


def _ssh_to_http(ssh_url: str) -> str:
    ssh_pattern = re.compile(r"git@([\w.]+):([\w-]+)/([\w-]+)")
    host, owner, repo = ssh_pattern.findall(ssh_url)[0]

    return f"https://{host}/{owner}/{repo}"


def _github_pull_request_url(host_url: str, branch_name: str) -> str:
    return f"{host_url}/pull/new/{branch_name}"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--push",
        action=argparse.BooleanOptionalAction,
        default=False,
    )
    args = parser.parse_args(argv)

    remote_url = _get_remote_url()
    if remote_url.startswith("git@"):
        http_url = _ssh_to_http(remote_url)
    else:
        http_url = remote_url

    branch_name = _get_branch_name()
    if http_url.startswith("https://github.com"):
        pull_request_url = _github_pull_request_url(http_url, branch_name)
    else:
        raise NotImplementedError(f"Method not supported for {http_url}")

    if args.push:
        try:
            print(_run_git_cmd(("push",), print_cmd=True))
        except Exception as e:
            print(colour(str(e), RED))
            return 1

    print(colour(f"Opening PR at: {pull_request_url}", GREEN))
    webbrowser.open(pull_request_url)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
